server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: entrada-service
          uri: http://entrada-service:8083
          predicates:
            - Path=/entrada/**
        - id: salida-service
          uri: http://salida-service:8084
          predicates:
            - Path=/salida/**
        - id: movimientos-service
          uri: http://movimientos-service:8085
          predicates:
            - Path=/movimientos/**
